### PR TITLE
Adding polish translation for validators.

### PR DESCRIPTION
**Pull request by piotrgradzinski**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| License       | MIT

Adding polish (pl) translation for validators.

### CODE REVIEW

**Comment by michalbiarda** [comment]
@piotrgradzinski You will not believe this, but I just started translating the same file and then thought "meh, maybe someone already did it". Thanks! :-)

**Comment by michalbiarda** [comment]
@piotrgradzinski BTW. There is one bug in your translation:

`<source>Your password must include at least one letter.</source>
<target>Hasło musi składać się z przynajmniej jednego znaku.</target>`

It should be "Hasło musi zawierać przynajmniej jedną literę."

**Comment by piotrgradzinski** [comment]
@michalbiarda - thank you very much for this! I've fixed that. On the other hand it would be great if you could take a look on the whole file. Just in case... It would be very valuable! Thank you!

**Comment by piotrgradzinski** [comment]
@michalbiarda - thank you once again. I was thinking about the point you've raised and I would stay with the initial proposition - I've consulted this as well with polish philologist to make sure. This particular sentence relates to the password as a whole, thats why I've used `składać się`, whereas the other ones refer more to what password should contain (`zawierać`). Like the whole password must have at least X characters vs. within the whole password we need to have characters from the specific character class. Hope this makes sense :)

**Comment by michalbiarda** [comment]
@piotrgradzinski Sounds legit! :+1:

**Comment by piotrgradzinski** [comment]
@sstok just wanted to say that the PR looks good and can be merged if you don't mind. Thank you!

**Comment by sstok** [comment]
Thank you @piotrgradzinski

**Pull request merged**
